#!/bin/csh
 source /remote/cad-rep/etc/.cshrc 
 module purge 
 module load ude-wrapper
 setenv MSIP_PROJ_ROOT /remote/cad-rep/projects 
 setenv MSIP_UDE_PROJ_ROOT /remote/cad-rep/projects 
 setenv UDE_HOME /u/alvaro
 unsetenv PASSWORD
 unsetenv CCSQA_PASSWORD
 cd /slowfs/dcopt103/alvaro/sgscratch/pcsqa/builds/hbm3-d763-hbm3-v2-tsmc3eff-12-ew-rel1.00_EWHardened/qa_step/check_ude_env_15M_1Xa_h_1Xb_v_1Xc_h_1Xd_v_1Ya_h_1Yb_v_4Y_hvhv_2Yy2Z_SHDMIM/work
 ude3 --projectType hbm3 --projectName d763-hbm3-v2-tsmc3eff-12-ew --releaseName rel1.00_EWHardened --metalStack 15M_1Xa_h_1Xb_v_1Xc_h_1Xd_v_1Ya_h_1Yb_v_4Y_hvhv_2Yy2Z_SHDMIM --nogui --no-dos --sourceShellFile /slowfs/dcopt103/alvaro/sgscratch/pcsqa/builds/hbm3-d763-hbm3-v2-tsmc3eff-12-ew-rel1.00_EWHardened/qa_step/check_ude_env_15M_1Xa_h_1Xb_v_1Xc_h_1Xd_v_1Ya_h_1Yb_v_4Y_hvhv_2Yy2Z_SHDMIM/work/sourceude --command "source /slowfs/dcopt103/alvaro/sgscratch/pcsqa/builds/hbm3-d763-hbm3-v2-tsmc3eff-12-ew-rel1.00_EWHardened/qa_step/check_ude_env_15M_1Xa_h_1Xb_v_1Xc_h_1Xd_v_1Ya_h_1Yb_v_4Y_hvhv_2Yy2Z_SHDMIM/work/exit_force.tcl" >& udelog &
 echo $! > pid.file
