pipeline {
    agent any
    stages {
        stage('clone') {
            checkout scm
        }

        stage('build') {
            steps {
                echo "Notify GitLab"
                updateGitlabCommitStatus name: "build", state: "pending"
                echo "build step goes here"
                updateGitlabCommitStatus name: "build", state: "success"
            }
        }
        stage('test') {
            steps {
                echo 'Notify GitLab'
                updateGitlabCommitStatus name: 'test', state: 'pending'
                echo 'test step goes here'
                updateGitlabCommitStatus name: 'test', state: 'success'
            }
        }
    }
}
