SHELL=tcsh
#
#
all:
	-cd sharedlib && $(MAKE)
	-cd ddr-ckt-rel/dev/main && $(MAKE)
	-cd ddr-utils/dev/main && $(MAKE)
	-cd ddr-utils-in08/dev/main && $(MAKE)
	-cd ddr-utils-lay/dev/main && $(MAKE)
	-cd ddr-utils-timing/dev/main && $(MAKE)
	
