default filter_layer_hier 1
default layer_hier_level 0
default find_limit unlimited
set layoutID [layout new abutment_acx4_a0_aM_aM_a0_ew -dbu 1e-9 -uu_per_dbu 0.001]
set pinID_dwc_ddrphyacx4_top_ew [layout new pin_dwc_ddrphyacx4_top_ew -dbu 1e-9 -uu_per_dbu 0.001]
layout open /slowfs/us01dwt2p315/mmuker/20220727_patrick/perforce_files/dwc_ddrphyacx4_top_ew.gds.gz#2 dwc_ddrphyacx4_top_ew
set boundary_bbox [layer bbox 108:0 -levels 0]
set x_dwc_ddrphyacx4_top_ew [lindex $boundary_bbox 2]
set y_dwc_ddrphyacx4_top_ew [lindex $boundary_bbox 3]
layout active $layoutID
layout reference add $pinID_dwc_ddrphyacx4_top_ew
layout reference add /slowfs/us01dwt2p315/mmuker/20220727_patrick/perforce_files/dwc_ddrphyacx4_top_ew.gds.gz#2
cell add aref dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 0]" 0 0
cell add aref pin_dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 0]" 0 0
hierarchy explode -cells pin_dwc_ddrphyacx4_top_ew
cell add aref dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 2*$y_dwc_ddrphyacx4_top_ew]" 0 1
cell add aref pin_dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 2*$y_dwc_ddrphyacx4_top_ew]" 0 1
hierarchy explode -cells pin_dwc_ddrphyacx4_top_ew
cell add aref dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 3*$y_dwc_ddrphyacx4_top_ew]" 0 1
cell add aref pin_dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 3*$y_dwc_ddrphyacx4_top_ew]" 0 1
hierarchy explode -cells pin_dwc_ddrphyacx4_top_ew
cell add aref dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 3*$y_dwc_ddrphyacx4_top_ew]" 0 0
cell add aref pin_dwc_ddrphyacx4_top_ew 1 1 [expr 0] [expr 0] "[expr 0] [expr 3*$y_dwc_ddrphyacx4_top_ew]" 0 0
hierarchy explode -cells pin_dwc_ddrphyacx4_top_ew
layout extract abutment_acx4_a0_aM_aM_a0_ew.gds.gz -format gds.gz -cell abutment_acx4_a0_aM_aM_a0_ew
exit
