namespace eval ::amd {

namespace export *

variable GVAR_amdLayVariables
array set GVAR_amdLayVariables {}

set GVAR_amdLayVariables(entryLayer) "text drawing"

set GVAR_amdLayVariables(amdLayoutAMDLSWUserRemovedLayerSets) ""
set GVAR_amdLayVariables(amdLayoutAMDLSWLayers) {{"Active" "act"} {"M1" "l01"} {"M2" "l02"} {"M3" "l03"} {"M4" "l04"} {"M5" "l05"} {"M6" "l06"} {"M7" "l07"} {"M8" "l08"} {"M9" "l09"} {"M10" "l10"} {"M11" "l11"} {"RDL" "l12"} {"Metals" "metal"} {"Vias" "vias"} {"VDD" "vdd"} {"VSS" "vss"} {"Labels" "label"} {"Pins" "pin"} {"Tracks" "track"} {"Blockage" "blockage"} {"Border" "border"} {"Implants" "implant"} {"ERC DRD" "ercmarker"} {"M1-M3" "layerset1"} {"M3-M5" "layerset2"} {"M5-M7" "layerset3"} {"M7-M10" "layerset4"} {"Fill" "fill"}}

set GVAR_amdLayVariables(amdLayoutAMDLSWFunctions) {{button "Change Layer" ::amd::_lsw::amdLayoutChangeLPP 1} {button "Function 1" callback 0}}
set GVAR_amdLayVariables(amdLayoutAMDLSWUserOwnedFunctions) ""

set GVAR_amdLayVariables(amdLayoutAlias,implant) {{"BH" "drawing"} {"PH" "drawing"} {"CG" "drawing"} {"VIA78" "drawing"} {"CL" "drawing"} {"EN" "drawing"} {"EP" "drawing"} {"HE" "drawing"} {"HF" "drawing"} {"HN" "drawing"} {"HP" "drawing"} {"I1" "drawing"} {"I2" "drawing"} {"I3" "drawing"} {"I4" "drawing"} {"I5" "drawing"} {"I6" "drawing"} {"IN" "drawing"} {"IP" "drawing"} {"JE" "drawing"} {"JF" "drawing"} {"JX" "drawing"} {"JZ" "drawing"} {"LW" "drawing"} {"N3" "drawing"} {"P0" "drawing"} {"P1" "drawing"} {"P2" "drawing"} {"PG" "drawing"} {"PP" "drawing"} {"RG" "drawing"} {"XW" "drawing"} {"AD" "drawing"} {"BF" "drawing"} {"TJ" "drawing"} {"WN" "drawing"} {"WP" "drawing"} {"ZL" "drawing"} {"RP" "drawing"} {"LV" "drawing"} {"DV" "drawing"} {"GP" "drawing"} {"GN" "drawing"} {"BV" "drawing"} {"CV" "drawing"} {"GY" "drawing"} {"IY" "drawing"} {"RESMOL" "drawing"} {"CD" "drawing"} {"XL" "drawing"} {"M0SALBLK" "drawing"} {"M0OPEN" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss11) {{"M11" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,met06) {{"M6" "drawing"} {"M6" "vss"} {"M6" "vddio"} {"M6" "vldt"} {"M6" "vtt"} {"M6" "vddr"} {"M6" "vmemp"} {"M6" "vmemio"} {"M6" "label"} {"M6" "pin"} {"M6" "e1"} {"M6" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,pin) {{"M1" "pin"} {"M2" "pin"} {"M3" "pin"} {"M4" "pin"} {"M5" "pin"} {"M6" "pin"} {"M7" "pin"} {"M8" "pin"} {"M9" "pin"} {"M10" "pin"} {"M11" "pin"} {"RDL" "pin"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss03) {{"M3" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,met09) {{"M9" "drawing"} {"M9" "vss"} {"M9" "vdd"} {"M9" "vddio"} {"M9" "vldt"} {"M9" "vtt"} {"M9" "vddr"} {"M9" "vmemp"} {"M9" "vmemio"} {"M9" "clock"} {"M9" "label"} {"M9" "pin"} {"M9" "e1"} {"M9" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,text10) {{"M10" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd02) {{"M2" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,vias) {{"M0POLY" "drawing"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"VIA34" "drawing"} {"VIA45" "drawing"} {"VIA56" "drawing"} {"VIA67" "drawing"} {"VIA78" "drawing"} {"VIA89" "drawing"} {"VIA910" "drawing"} {"VIA1011" "drawing"} {"RDLVIA" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,text10) {{"M10" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd02) {{"M2" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd05) {{"M5" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,l09) {{"M9" "drawing"} {"M9" "vss"} {"M9" "vdd"} {"M9" "vddio"} {"M9" "vldt"} {"M9" "vtt"} {"M9" "vddr"} {"M9" "vmemp"} {"M9" "vmemio"} {"M9" "clock"} {"M9" "label"} {"M9" "pin"} {"M9" "e1"} {"M9" "e2"} {"VIA89" "drawing"} {"VIA910" "drawing"} {"TRACK" "m9"} {"M9" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,metal) {{"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"} {"M4" "drawing"} {"M4" "vss"} {"M4" "vddio"} {"M4" "vldt"} {"M4" "vtt"} {"M4" "vddr"} {"M4" "vmemp"} {"M4" "vmemio"} {"M4" "label"} {"M4" "pin"} {"M4" "e1"} {"M4" "e2"} {"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"} {"M6" "drawing"} {"M6" "vss"} {"M6" "vddio"} {"M6" "vldt"} {"M6" "vtt"} {"M6" "vddr"} {"M6" "vmemp"} {"M6" "vmemio"} {"M6" "label"} {"M6" "pin"} {"M6" "e1"} {"M6" "e2"} {"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"} {"M8" "drawing"} {"M8" "vss"} {"M8" "vdd"} {"M8" "vddio"} {"M8" "vldt"} {"M8" "vtt"} {"M8" "vddr"} {"M8" "vmemp"} {"M8" "vmemio"} {"M8" "clock"} {"M8" "label"} {"M8" "pin"} {"M8" "e1"} {"M8" "e2"} {"M9" "drawing"} {"M9" "vss"} {"M9" "vdd"} {"M9" "vddio"} {"M9" "vldt"} {"M9" "vtt"} {"M9" "vddr"} {"M9" "vmemp"} {"M9" "vmemio"} {"M9" "clock"} {"M9" "label"} {"M9" "pin"} {"M9" "e1"} {"M9" "e2"} {"M10" "drawing"} {"M10" "vss"} {"M10" "vdd"} {"M10" "vddio"} {"M10" "vldt"} {"M10" "vtt"} {"M10" "vddr"} {"M10" "vmemp"} {"M10" "vmemio"} {"M10" "clock"} {"M10" "label"} {"M10" "pin"} {"M10" "e1"} {"M10" "e2"} {"M11" "drawing"} {"M11" "vss"} {"M11" "vdd"} {"M11" "vddio"} {"M11" "vldt"} {"M11" "vtt"} {"M11" "vddr"} {"M11" "vmemp"} {"M11" "vmemio"} {"M11" "clock"} {"M11" "label"} {"M11" "pin"} {"M11" "e1"} {"M11" "e2"} {"RDL" "drawing"} {"RDL" "vss"} {"RDL" "vdd"} {"RDL" "vddio"} {"RDL" "vldt"} {"RDL" "vtt"} {"RDL" "vddr"} {"RDL" "vmemp"} {"RDL" "vmemio"} {"RDL" "clock"} {"RDL" "label"} {"RDL" "pin"} {"RDL" "e1"} {"RDL" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,act) {{"NWELL" "drawing"} {"NW" "pin"} {"NWELL" "label"} {"NWRES" "lvs"} {"DIFF" "drawing"} {"PARAPOLY" "marker"} {"PARAPOLY2" "marker"} {"POLY" "drawing"} {"TRACK" "pc"} {"TS" "drawing"} {"TS" "dummy"} {"M0DIFF2" "drawing"} {"M0POLY" "drawing"} {"VIA0" "drawing"} {"ESDHBM" "drc"} {"RESMOL" "drawing"} {"RESMOLTERM" "drawing"} {"PCSTP2" "drawing"} {"PCSTP4" "drawing"} {"PCSTP6" "drawing"} {"PCSTP8" "drawing"} {"PCSTP10" "drawing"} {"PCSTN2" "drawing"} {"PCSTN4" "drawing"} {"PCSTN6" "drawing"} {"PCSTN8" "drawing"} {"PCSTN10" "drawing"} {"SEPSUB" "label"} {"FIN_CUT" "drawing"} {"ROTDEV" "marker"} {"ISODEV" "drawing"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss02) {{"M2" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd03) {{"M3" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,text06) {{"M6" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,labels) {{"POLY" "label"} {"M1" "label"} {"M2" "label"} {"M3" "label"} {"M4" "label"} {"M5" "label"} {"M6" "label"} {"M7" "label"} {"M8" "label"} {"M9" "label"} {"M10" "label"} {"M11" "label"} {"RDL" "label"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock10) {{"M10" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd08) {{"M8" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd01) {{"M1" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd03) {{"M3" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,fill) {{"DIFF" "dummy"} {"RX" "fillOPC"} {"DIFF" "dummycell1"} {"DIFF" "dummycell2"} {"DIFF_CUT" "marker"} {"POLY" "dummy"} {"POLY" "fillOPC"} {"POLY" "dummycell1"} {"POLY" "dummycell2"} {"FN" "dummy"} {"FN" "fillOPC"} {"FIN" "dummycell1"} {"FIN" "dummycell2"} {"FN" "cfmandrel"} {"RC" "dummy"} {"RC" "fillOPC"} {"FIN_CUT" "dummycell1"} {"FIN_CUT" "dummycell2"} {"TEMP2" "temporary"} {"CT" "dummycell1"} {"CT" "dummycell2"} {"TT" "dummy"} {"TT" "fillOPC"} {"TT" "dummycell1"} {"TT" "dummycell2"} {"TT" "cfillholetr"} {"M0SALBLK" "dummy"} {"M0SALBLK" "fillOPC"} {"M0SALBLK" "dummycell1"} {"M0SALBLK" "dummycell2"} {"TEMP1" "dummycell1"} {"TEMP1" "dummycell2"} {"TEMP3" "temporary"} {"M0DIFF2" "cfill_e1"} {"M0DIFF2" "cfill_e2"} {"M0DIFF2" "cfillcm_e1"} {"M0DIFF2" "cfillcm_e2"} {"M0DIFF2" "cfillopc_e1"} {"M0DIFF2" "cfillopc_e2"} {"M0DIFF2" "cfilltr_e1"} {"M0DIFF2" "cfilltr_e2"} {"M0POLY" "cfill_e1"} {"M0POLY" "cfill_e2"} {"M0POLY" "cfillopc_e1"} {"M0POLY" "cfillopc_e2"} {"M0POLY" "cfilltr_e1"} {"M0POLY" "cfilltr_e2"} {"M0POLY" "cfillcm_e1"} {"M0POLY" "cfillcm_e2"} {"PFETCFILLTR" "drawing"} {"NFETCFILLTR" "drawing"} {"TRANSISTORCELL" "drawing"} {"COMBORXPC" "drawing"} {"M1" "dummy_dpl1"} {"M1" "dummy_dpl2"} {"M1" "dummy_dpl1opc"} {"M1" "dummy_dpl2opc"} {"VIA12" "dummy"} {"M2" "dummy_dpl1"} {"M2" "dummy_dpl2"} {"M2" "dummy_dpl1opc"} {"M2" "dummy_dpl2opc"} {"VIA23" "dummy"} {"M3" "dummy_dpl1"} {"M3" "dummy_dpl2"} {"M3" "dummy_dpl1opc"} {"M3" "dummy_dpl2opc"} {"VIA34" "dummy"} {"M4" "dummy"} {"M4" "fillOPC"} {"VIA45" "dummy"} {"M5" "dummy"} {"M5" "fillOPC"} {"VIA56" "dummy"} {"M6" "dummy"} {"M6" "fillOPC"} {"VIA67" "dummy"} {"M7" "dummy"} {"M7" "fillOPC"} {"M8" "dummy"} {"M8" "fillOPC"} {"VIA89" "dummy"} {"M9" "dummy"} {"M9" "fillOPC"} {"VIA910" "dummy"} {"M10" "dummy"} {"M11" "dummy"} {"RDL" "dummy"} {"QT" "dummy"} {"HT" "dummy"} {"CK" "dummy"}}
set GVAR_amdLayVariables(amdLayoutAlias,text05) {{"M5" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,met02) {{"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock11) {{"M11" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss05) {{"M5" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,l12) {{"RDL" "drawing"} {"RDL" "vss"} {"RDL" "vdd"} {"RDL" "vddio"} {"RDL" "vldt"} {"RDL" "vtt"} {"RDL" "vddr"} {"RDL" "vmemp"} {"RDL" "vmemio"} {"RDL" "clock"} {"RDL" "label"} {"RDL" "pin"} {"RDL" "e1"} {"RDL" "e2"} {"RDLVIA" "drawing"} {"TRACK" "m12"} {"RDL" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,text03) {{"M3" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,always_on) {{"y0" "drawing"} {"y0" "flight"} {"y1" "drawing"} {"y1" "flight"} {"y2" "drawing"} {"y2" "flight"} {"y3" "drawing"} {"y3" "flight"} {"y4" "drawing"} {"y4" "flight"} {"y5" "drawing"} {"y5" "flight"} {"y6" "drawing"} {"y6" "flight"} {"y7" "drawing"} {"y7" "flight"} {"y8" "drawing"} {"y8" "flight"} {"y9" "drawing"} {"y9" "flight"} {"stretch" "drawing"} {"instance" "drawing"} {"hilite" "drawing"} {"hilite" "drawing1"} {"hilite" "drawing2"} {"hilite" "drawing3"} {"hilite" "drawing4"} {"hilite" "drawing5"} {"hilite" "drawing6"} {"hilite" "drawing7"} {"hilite" "drawing8"} {"hilite" "drawing9"} {"annotate" "drawing"} {"annotate" "drawing1"} {"annotate" "drawing2"} {"annotate" "drawing3"} {"annotate" "drawing4"} {"annotate" "drawing5"} {"annotate" "drawing6"} {"annotate" "drawing7"} {"annotate" "drawing8"} {"annotate" "drawing9"} {"Unrouted" "drawing"} {"Unrouted" "drawing1"} {"Unrouted" "drawing2"} {"Unrouted" "drawing3"} {"Unrouted" "drawing4"} {"Unrouted" "drawing5"} {"Unrouted" "drawing6"} {"Unrouted" "drawing7"} {"Unrouted" "drawing8"} {"Unrouted" "drawing9"} {"instance" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,text08) {{"M8" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,layerset3) {{"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"} {"VIA45" "drawing"} {"VIA56" "drawing"} {"TRACK" "m5"} {"TEXTJNK" "drawing"} {"M6" "drawing"} {"M6" "vss"} {"M6" "vddio"} {"M6" "vldt"} {"M6" "vtt"} {"M6" "vddr"} {"M6" "vmemp"} {"M6" "vmemio"} {"M6" "label"} {"M6" "pin"} {"M6" "e1"} {"M6" "e2"} {"VIA56" "drawing"} {"VIA67" "drawing"} {"TRACK" "m6"} {"TEXTJNK" "drawing"} {"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"} {"VIA67" "drawing"} {"VIA78" "drawing"} {"TRACK" "m7"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd) {{"M1" "vdd"} {"M2" "vdd"} {"M3" "vdd"} {"M7" "vdd"} {"M8" "vdd"} {"M9" "vdd"} {"M10" "vdd"} {"M11" "vdd"} {"RDL" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,text12) {{"RDL" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,l04) {{"M4" "drawing"} {"M4" "vss"} {"M4" "vddio"} {"M4" "vldt"} {"M4" "vtt"} {"M4" "vddr"} {"M4" "vmemp"} {"M4" "vmemio"} {"M4" "label"} {"M4" "pin"} {"M4" "e1"} {"M4" "e2"} {"VIA34" "drawing"} {"VIA45" "drawing"} {"TRACK" "m4"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,l06) {{"M6" "drawing"} {"M6" "vss"} {"M6" "vddio"} {"M6" "vldt"} {"M6" "vtt"} {"M6" "vddr"} {"M6" "vmemp"} {"M6" "vmemio"} {"M6" "label"} {"M6" "pin"} {"M6" "e1"} {"M6" "e2"} {"VIA56" "drawing"} {"VIA67" "drawing"} {"TRACK" "m6"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd12) {{"RDL" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,text04) {{"M4" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd07) {{"M7" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss08) {{"M8" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,macros) {{"NWELL" "drawing"} {"NW" "pin"} {"NWELL" "label"} {"NWRES" "lvs"} {"DIFF" "drawing"} {"PARAPOLY" "marker"} {"PARAPOLY2" "marker"} {"POLY" "drawing"} {"TRACK" "pc"} {"TS" "drawing"} {"TS" "dummy"} {"M0DIFF2" "drawing"} {"M0POLY" "drawing"} {"VIA0" "drawing"} {"ESDHBM" "drc"} {"RESMOL" "drawing"} {"RESMOLTERM" "drawing"} {"PCSTP2" "drawing"} {"PCSTP4" "drawing"} {"PCSTP6" "drawing"} {"PCSTP8" "drawing"} {"PCSTP10" "drawing"} {"PCSTN2" "drawing"} {"PCSTN4" "drawing"} {"PCSTN6" "drawing"} {"PCSTN8" "drawing"} {"PCSTN10" "drawing"} {"SEPSUB" "label"} {"RC" "drawing"} {"ROTDEV" "marker"} {"ISODEV" "drawing"} {"TEXTJNK" "drawing"} {"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"TRACK" "m1"} {"M1" "gnd"} {"TEXTJNK" "drawing"} {"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"TRACK" "m2"} {"M2" "gnd"} {"TEXTJNK" "drawing"} {"prBoundary" "boundary"} {"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"} {"VIA23" "drawing"} {"VIA34" "drawing"} {"TRACK" "m3"} {"M3" "gnd"} {"TEXTJNK" "drawing"} {"M4" "drawing"} {"M4" "vss"} {"M4" "vddio"} {"M4" "vldt"} {"M4" "vtt"} {"M4" "vddr"} {"M4" "vmemp"} {"M4" "vmemio"} {"M4" "label"} {"M4" "pin"} {"M4" "e1"} {"M4" "e2"} {"VIA34" "drawing"} {"VIA45" "drawing"} {"TRACK" "m4"} {"TEXTJNK" "drawing"} {"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"} {"VIA45" "drawing"} {"VIA56" "drawing"} {"TRACK" "m5"} {"TEXTJNK" "drawing"} {"M6" "drawing"} {"M6" "vss"} {"M6" "vddio"} {"M6" "vldt"} {"M6" "vtt"} {"M6" "vddr"} {"M6" "vmemp"} {"M6" "vmemio"} {"M6" "label"} {"M6" "pin"} {"M6" "e1"} {"M6" "e2"} {"VIA56" "drawing"} {"VIA67" "drawing"} {"TRACK" "m6"} {"TEXTJNK" "drawing"} {"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"} {"VIA67" "drawing"} {"VIA78" "drawing"} {"TRACK" "m7"} {"TEXTJNK" "drawing"} {"M8" "drawing"} {"M8" "vss"} {"M8" "vdd"} {"M8" "vddio"} {"M8" "vldt"} {"M8" "vtt"} {"M8" "vddr"} {"M8" "vmemp"} {"M8" "vmemio"} {"M8" "clock"} {"M8" "label"} {"M8" "pin"} {"M8" "e1"} {"M8" "e2"} {"VIA78" "drawing"} {"VIA89" "drawing"} {"TRACK" "m8"} {"M8" "gnd"} {"TEXTJNK" "drawing"} {"prBoundary" "boundary"}}
set GVAR_amdLayVariables(amdLayoutAlias,obsolete) {{"M1" "blockage"} {"M2" "blockage"} {"M3" "blockage"} {"M4" "blockage"} {"M5" "blockage"} {"M6" "blockage"} {"M7" "blockage"} {"M8" "blockage"} {"M9" "blockage"} {"M10" "blockage"} {"M11" "blockage"} {"RDL" "blockage"} {"M0POLY" "blockage"} {"VIA0" "blockage"} {"VIA12" "blockage"} {"VIA23" "blockage"} {"VIA34" "blockage"} {"VIA45" "blockage"} {"VIA56" "blockage"} {"VIA67" "blockage"} {"CK" "blockage"} {"VIA89" "blockage"} {"VIA910" "blockage"} {"VIA1011" "blockage"} {"RDLVIA" "blockage"} {"M1" "keepout"} {"M2" "keepout"} {"M3" "keepout"} {"M4" "keepout"} {"M5" "keepout"} {"M6" "keepout"} {"M7" "keepout"} {"M8" "keepout"} {"M9" "keepout"} {"M10" "keepout"} {"M11" "keepout"} {"RDL" "keepout"} {"POLY" "keepout"} {"DIFF" "keepout"}}
set GVAR_amdLayVariables(amdLayoutAlias,met10) {{"M10" "drawing"} {"M10" "vss"} {"M10" "vdd"} {"M10" "vddio"} {"M10" "vldt"} {"M10" "vtt"} {"M10" "vddr"} {"M10" "vmemp"} {"M10" "vmemio"} {"M10" "clock"} {"M10" "label"} {"M10" "pin"} {"M10" "e1"} {"M10" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,text02) {{"M2" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,layerset1) {{"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"TRACK" "m1"} {"M1" "gnd"} {"TEXTJNK" "drawing"} {"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"TRACK" "m2"} {"M2" "gnd"} {"TEXTJNK" "drawing"} {"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"} {"VIA23" "drawing"} {"VIA34" "drawing"} {"TRACK" "m3"} {"M3" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,all) {}
set GVAR_amdLayVariables(amdLayoutAlias,l10) {{"M10" "drawing"} {"M10" "vss"} {"M10" "vdd"} {"M10" "vddio"} {"M10" "vldt"} {"M10" "vtt"} {"M10" "vddr"} {"M10" "vmemp"} {"M10" "vmemio"} {"M10" "clock"} {"M10" "label"} {"M10" "pin"} {"M10" "e1"} {"M10" "e2"} {"VIA910" "drawing"} {"VIA1011" "drawing"} {"TRACK" "m10"} {"M10" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,macro) {{"NWELL" "drawing"} {"NW" "pin"} {"NWELL" "label"} {"NWRES" "lvs"} {"DIFF" "drawing"} {"PARAPOLY" "marker"} {"PARAPOLY2" "marker"} {"POLY" "drawing"} {"TRACK" "pc"} {"TS" "drawing"} {"TS" "dummy"} {"M0DIFF2" "drawing"} {"M0POLY" "drawing"} {"VIA0" "drawing"} {"ESDHBM" "drc"} {"RESMOL" "drawing"} {"RESMOLTERM" "drawing"} {"PCSTP2" "drawing"} {"PCSTP4" "drawing"} {"PCSTP6" "drawing"} {"PCSTP8" "drawing"} {"PCSTP10" "drawing"} {"PCSTN2" "drawing"} {"PCSTN4" "drawing"} {"PCSTN6" "drawing"} {"PCSTN8" "drawing"} {"PCSTN10" "drawing"} {"SEPSUB" "label"} {"RC" "drawing"} {"ROTDEV" "marker"} {"ISODEV" "drawing"} {"TEXTJNK" "drawing"} {"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"TRACK" "m1"} {"M1" "gnd"} {"TEXTJNK" "drawing"} {"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"TRACK" "m2"} {"M2" "gnd"} {"TEXTJNK" "drawing"} {"prBoundary" "boundary"} {"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"} {"VIA23" "drawing"} {"VIA34" "drawing"} {"TRACK" "m3"} {"M3" "gnd"} {"TEXTJNK" "drawing"} {"M4" "drawing"} {"M4" "vss"} {"M4" "vddio"} {"M4" "vldt"} {"M4" "vtt"} {"M4" "vddr"} {"M4" "vmemp"} {"M4" "vmemio"} {"M4" "label"} {"M4" "pin"} {"M4" "e1"} {"M4" "e2"} {"VIA34" "drawing"} {"VIA45" "drawing"} {"TRACK" "m4"} {"TEXTJNK" "drawing"} {"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"} {"VIA45" "drawing"} {"VIA56" "drawing"} {"TRACK" "m5"} {"TEXTJNK" "drawing"} {"M6" "drawing"} {"M6" "vss"} {"M6" "vddio"} {"M6" "vldt"} {"M6" "vtt"} {"M6" "vddr"} {"M6" "vmemp"} {"M6" "vmemio"} {"M6" "label"} {"M6" "pin"} {"M6" "e1"} {"M6" "e2"} {"VIA56" "drawing"} {"VIA67" "drawing"} {"TRACK" "m6"} {"TEXTJNK" "drawing"} {"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"} {"VIA67" "drawing"} {"VIA78" "drawing"} {"TRACK" "m7"} {"TEXTJNK" "drawing"} {"M8" "drawing"} {"M8" "vss"} {"M8" "vdd"} {"M8" "vddio"} {"M8" "vldt"} {"M8" "vtt"} {"M8" "vddr"} {"M8" "vmemp"} {"M8" "vmemio"} {"M8" "clock"} {"M8" "label"} {"M8" "pin"} {"M8" "e1"} {"M8" "e2"} {"VIA78" "drawing"} {"VIA89" "drawing"} {"TRACK" "m8"} {"M8" "gnd"} {"TEXTJNK" "drawing"} {"prBoundary" "boundary"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss07) {{"M7" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,stdcell) {{"NWELL" "drawing"} {"NW" "pin"} {"NWELL" "label"} {"NWRES" "lvs"} {"DIFF" "drawing"} {"PARAPOLY" "marker"} {"PARAPOLY2" "marker"} {"POLY" "drawing"} {"TRACK" "pc"} {"TS" "drawing"} {"TS" "dummy"} {"M0DIFF2" "drawing"} {"M0POLY" "drawing"} {"VIA0" "drawing"} {"ESDHBM" "drc"} {"RESMOL" "drawing"} {"RESMOLTERM" "drawing"} {"PCSTP2" "drawing"} {"PCSTP4" "drawing"} {"PCSTP6" "drawing"} {"PCSTP8" "drawing"} {"PCSTP10" "drawing"} {"PCSTN2" "drawing"} {"PCSTN4" "drawing"} {"PCSTN6" "drawing"} {"PCSTN8" "drawing"} {"PCSTN10" "drawing"} {"SEPSUB" "label"} {"RC" "drawing"} {"ROTDEV" "marker"} {"ISODEV" "drawing"} {"TEXTJNK" "drawing"} {"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"TRACK" "m1"} {"M1" "gnd"} {"TEXTJNK" "drawing"} {"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"TRACK" "m2"} {"M2" "gnd"} {"TEXTJNK" "drawing"} {"prBoundary" "boundary"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss12) {{"RDL" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd11) {{"M11" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,met08) {{"M8" "drawing"} {"M8" "vss"} {"M8" "vdd"} {"M8" "vddio"} {"M8" "vldt"} {"M8" "vtt"} {"M8" "vddr"} {"M8" "vmemp"} {"M8" "vmemio"} {"M8" "clock"} {"M8" "label"} {"M8" "pin"} {"M8" "e1"} {"M8" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd04) {{"M4" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss) {{"M1" "vss"} {"M2" "vss"} {"M3" "vss"} {"M4" "vss"} {"M5" "vss"} {"M6" "vss"} {"M7" "vss"} {"M8" "vss"} {"M9" "vss"} {"M10" "vss"} {"M11" "vss"} {"RDL" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,layerset4) {{"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"} {"VIA67" "drawing"} {"VIA78" "drawing"} {"TRACK" "m7"} {"TEXTJNK" "drawing"} {"M8" "drawing"} {"M8" "vss"} {"M8" "vdd"} {"M8" "vddio"} {"M8" "vldt"} {"M8" "vtt"} {"M8" "vddr"} {"M8" "vmemp"} {"M8" "vmemio"} {"M8" "clock"} {"M8" "label"} {"M8" "pin"} {"M8" "e1"} {"M8" "e2"} {"VIA78" "drawing"} {"VIA89" "drawing"} {"TRACK" "m8"} {"M8" "gnd"} {"TEXTJNK" "drawing"} {"M9" "drawing"} {"M9" "vss"} {"M9" "vdd"} {"M9" "vddio"} {"M9" "vldt"} {"M9" "vtt"} {"M9" "vddr"} {"M9" "vmemp"} {"M9" "vmemio"} {"M9" "clock"} {"M9" "label"} {"M9" "pin"} {"M9" "e1"} {"M9" "e2"} {"VIA89" "drawing"} {"VIA910" "drawing"} {"TRACK" "m9"} {"M9" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,l07) {{"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"} {"VIA67" "drawing"} {"VIA78" "drawing"} {"TRACK" "m7"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,text09) {{"M9" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,met05) {{"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,met03) {{"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd06) {{"M6" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,met12) {{"RDL" "drawing"} {"RDL" "vss"} {"RDL" "vdd"} {"RDL" "vddio"} {"RDL" "vldt"} {"RDL" "vtt"} {"RDL" "vddr"} {"RDL" "vmemp"} {"RDL" "vmemio"} {"RDL" "clock"} {"RDL" "label"} {"RDL" "pin"} {"RDL" "e1"} {"RDL" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss01) {{"M1" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock02) {{"M2" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd06) {{"M6" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd05) {{"M5" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd10) {{"M10" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd10) {{"M10" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,l01) {{"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"TRACK" "m1"} {"M1" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock03) {{"M3" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd07) {{"M7" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock06) {{"M6" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss06) {{"M6" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,label) {{"POLY" "label"} {"M1" "label"} {"M2" "label"} {"M3" "label"} {"M4" "label"} {"M5" "label"} {"M6" "label"} {"M7" "label"} {"M8" "label"} {"M9" "label"} {"M10" "label"} {"M11" "label"} {"RDL" "label"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,track) {{"TRACK" "m1"} {"TRACK" "m2"} {"TRACK" "m3"} {"TRACK" "m4"} {"TRACK" "m5"} {"TRACK" "m6"} {"TRACK" "m7"} {"TRACK" "m8"} {"TRACK" "m9"} {"TRACK" "m10"} {"TRACK" "m11"} {"TRACK" "m12"}}
set GVAR_amdLayVariables(amdLayoutAlias,ercmarker) {{"ACTIVE" "erc"}}
set GVAR_amdLayVariables(amdLayoutAlias,text11) {{"M11" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd04) {{"M4" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,l08) {{"M8" "drawing"} {"M8" "vss"} {"M8" "vdd"} {"M8" "vddio"} {"M8" "vldt"} {"M8" "vtt"} {"M8" "vddr"} {"M8" "vmemp"} {"M8" "vmemio"} {"M8" "clock"} {"M8" "label"} {"M8" "pin"} {"M8" "e1"} {"M8" "e2"} {"VIA78" "drawing"} {"VIA89" "drawing"} {"M8" "track"} {"TRACK" "m8"} {"M8" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,met04) {{"M4" "drawing"} {"M4" "vss"} {"M4" "vddio"} {"M4" "vldt"} {"M4" "vtt"} {"M4" "vddr"} {"M4" "vmemp"} {"M4" "vmemio"} {"M4" "label"} {"M4" "pin"} {"M4" "e1"} {"M4" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,met07) {{"M7" "drawing"} {"M7" "vss"} {"M7" "vdd"} {"M7" "vddio"} {"M7" "vldt"} {"M7" "vtt"} {"M7" "vddr"} {"M7" "vmemp"} {"M7" "vmemio"} {"M7" "clock"} {"M7" "label"} {"M7" "pin"} {"M7" "e1"} {"M7" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock05) {{"M5" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock07) {{"M7" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,text01) {{"M1" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,layerset2) {{"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"} {"VIA23" "drawing"} {"VIA34" "drawing"} {"M3" "track"} {"TRACK" "m3"} {"M3" "gnd"} {"TEXTJNK" "drawing"} {"M4" "drawing"} {"M4" "vss"} {"M4" "vddio"} {"M4" "vldt"} {"M4" "vtt"} {"M4" "vddr"} {"M4" "vmemp"} {"M4" "vmemio"} {"M4" "label"} {"M4" "pin"} {"M4" "e1"} {"M4" "e2"} {"VIA34" "drawing"} {"VIA45" "drawing"} {"M4" "track"} {"TRACK" "m4"} {"TEXTJNK" "drawing"} {"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"} {"VIA45" "drawing"} {"VIA56" "drawing"} {"M5" "track"} {"TRACK" "m5"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,l05) {{"M5" "drawing"} {"M5" "vss"} {"M5" "vddio"} {"M5" "vldt"} {"M5" "vtt"} {"M5" "vddr"} {"M5" "vmemp"} {"M5" "vmemio"} {"M5" "label"} {"M5" "pin"} {"M5" "e1"} {"M5" "e2"} {"VIA45" "drawing"} {"VIA56" "drawing"} {"M5" "track"} {"TRACK" "m5"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd12) {{"RDL" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,stdcells) {{"NWELL" "drawing"} {"NW" "pin"} {"NWELL" "label"} {"NWRES" "lvs"} {"DIFF" "drawing"} {"PARAPOLY" "marker"} {"PARAPOLY2" "marker"} {"POLY" "drawing"} {"TRACK" "pc"} {"TS" "drawing"} {"TS" "dummy"} {"M0DIFF2" "drawing"} {"M0POLY" "drawing"} {"VIA0" "drawing"} {"ESDHBM" "drc"} {"RESMOL" "drawing"} {"RESMOLTERM" "drawing"} {"PCSTP2" "drawing"} {"PCSTP4" "drawing"} {"PCSTP6" "drawing"} {"PCSTP8" "drawing"} {"PCSTP10" "drawing"} {"PCSTN2" "drawing"} {"PCSTN4" "drawing"} {"PCSTN6" "drawing"} {"PCSTN8" "drawing"} {"PCSTN10" "drawing"} {"SEPSUB" "label"} {"RC" "drawing"} {"ROTDEV" "marker"} {"ISODEV" "drawing"} {"TEXTJNK" "drawing"} {"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"} {"VIA0" "drawing"} {"VIA12" "drawing"} {"M1" "track"} {"TRACK" "m1"} {"M1" "gnd"} {"TEXTJNK" "drawing"} {"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"M2" "track"} {"TRACK" "m2"} {"M2" "gnd"} {"TEXTJNK" "drawing"} {"prBoundary" "boundary"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd11) {{"M11" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd08) {{"M8" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,l02) {{"M2" "drawing"} {"M2" "vss"} {"M2" "vdd"} {"M2" "vddio"} {"M2" "vldt"} {"M2" "vtt"} {"M2" "vddr"} {"M2" "vmemp"} {"M2" "vmemio"} {"M2" "clock"} {"M2" "label"} {"M2" "pin"} {"M2" "e1"} {"M2" "e2"} {"VIA12" "drawing"} {"VIA23" "drawing"} {"M2" "track"} {"TRACK" "m2"} {"M2" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock04) {{"M4" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,layerset5) {{"M9" "drawing"} {"M9" "vss"} {"M9" "vdd"} {"M9" "vddio"} {"M9" "vldt"} {"M9" "vtt"} {"M9" "vddr"} {"M9" "vmemp"} {"M9" "vmemio"} {"M9" "clock"} {"M9" "label"} {"M9" "pin"} {"M9" "e1"} {"M9" "e2"} {"VIA89" "drawing"} {"VIA910" "drawing"} {"M9" "track"} {"TRACK" "m9"} {"M9" "gnd"} {"TEXTJNK" "drawing"} {"M10" "drawing"} {"M10" "vss"} {"M10" "vdd"} {"M10" "vddio"} {"M10" "vldt"} {"M10" "vtt"} {"M10" "vddr"} {"M10" "vmemp"} {"M10" "vmemio"} {"M10" "clock"} {"M10" "label"} {"M10" "pin"} {"M10" "e1"} {"M10" "e2"} {"VIA910" "drawing"} {"VIA1011" "drawing"} {"M10" "track"} {"TRACK" "m10"} {"M10" "gnd"} {"TEXTJNK" "drawing"} {"M11" "drawing"} {"M11" "vss"} {"M11" "vdd"} {"M11" "vddio"} {"M11" "vldt"} {"M11" "vtt"} {"M11" "vddr"} {"M11" "vmemp"} {"M11" "vmemio"} {"M11" "clock"} {"M11" "label"} {"M11" "pin"} {"M11" "e1"} {"M11" "e2"} {"VIA1011" "drawing"} {"RDLVIA" "drawing"} {"M11" "track"} {"TRACK" "m11"} {"M11" "gnd"} {"TEXTJNK" "drawing"} {"RDL" "drawing"} {"RDL" "vss"} {"RDL" "vdd"} {"RDL" "vddio"} {"RDL" "vldt"} {"RDL" "vtt"} {"RDL" "vddr"} {"RDL" "vmemp"} {"RDL" "vmemio"} {"RDL" "clock"} {"RDL" "label"} {"RDL" "pin"} {"RDL" "e1"} {"RDL" "e2"} {"RDLVIA" "drawing"} {"TRACK" "m12"} {"RDL" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,blockage) {{"M1" "blockage"} {"M2" "blockage"} {"M3" "blockage"} {"M4" "blockage"} {"M5" "blockage"} {"M6" "blockage"} {"M7" "blockage"} {"M8" "blockage"} {"M9" "blockage"} {"M10" "blockage"} {"M11" "blockage"} {"RDL" "blockage"} {"PC" "blockage"} {"M0POLY" "blockage"} {"VIA0" "blockage"} {"VIA12" "blockage"} {"VIA23" "blockage"} {"VIA34" "blockage"} {"VIA45" "blockage"} {"VIA56" "blockage"} {"VIA67" "blockage"} {"CK" "blockage"} {"VIA89" "blockage"} {"VIA910" "blockage"} {"VIA1011" "blockage"}}
set GVAR_amdLayVariables(amdLayoutAlias,l11) {{"M11" "drawing"} {"M11" "vss"} {"M11" "vdd"} {"M11" "vddio"} {"M11" "vldt"} {"M11" "vtt"} {"M11" "vddr"} {"M11" "vmemp"} {"M11" "vmemio"} {"M11" "clock"} {"M11" "label"} {"M11" "pin"} {"M11" "e1"} {"M11" "e2"} {"VIA1011" "drawing"} {"RDLVIA" "drawing"} {"TRACK" "m11"} {"M11" "gnd"} {"TEXTJNK" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock12) {{"RDL" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,met11) {{"M11" "drawing"} {"M11" "vss"} {"M11" "vdd"} {"M11" "vddio"} {"M11" "vldt"} {"M11" "vtt"} {"M11" "vddr"} {"M11" "vmemp"} {"M11" "vmemio"} {"M11" "clock"} {"M11" "label"} {"M11" "pin"} {"M11" "e1"} {"M11" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd02) {{"M2" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,always_off) nil
set GVAR_amdLayVariables(amdLayoutAlias,border) {{"prBoundary" "boundary"}}
set GVAR_amdLayVariables(amdLayoutAlias,l03) {{"M3" "drawing"} {"M3" "vss"} {"M3" "vdd"} {"M3" "vddio"} {"M3" "vldt"} {"M3" "vtt"} {"M3" "vddr"} {"M3" "vmemp"} {"M3" "vmemio"} {"M3" "clock"} {"M3" "label"} {"M3" "pin"} {"M3" "e1"} {"M3" "e2"} {"VIA23" "drawing"} {"VIA34" "drawing"} {"M3" "track"} {"TRACK" "m3"} {"M3" "gnd"} {"TEXTJNK" "drawing"} {"m3" "drawing"}}
set GVAR_amdLayVariables(amdLayoutAlias,vdd09) {{"M9" "vdd"}}
set GVAR_amdLayVariables(amdLayoutAlias,met01) {{"M1" "drawing"} {"M1" "vss"} {"M1" "vdd"} {"M1" "vddio"} {"M1" "vldt"} {"M1" "vtt"} {"M1" "vddr"} {"M1" "vmemp"} {"M1" "vmemio"} {"M1" "clock"} {"M1" "label"} {"M1" "pin"} {"M1" "e1"} {"M1" "e2"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd01) {{"M1" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss04) {{"M4" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,gnd09) {{"M9" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss09) {{"M9" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock01) {{"M1" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,vss10) {{"M10" "vss"}}
set GVAR_amdLayVariables(amdLayoutAlias,text07) {{"M7" "label"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock09) {{"M9" "clock"}}
set GVAR_amdLayVariables(amdLayoutAlias,clock08) {{"M8" "clock"}}

set GVAR_amdLayVariables(amdLayoutAMDLSWHiddenLayerSets) {{"StdCells" "stdcells"} {"Macros" "macros"}}
# Added by norayra. AMD need to feed correct information here.
set GVAR_amdLayVariables(amdMetLayers) {M1 M2 M3 M4 M5 M6}
set GVAR_amdLayVariables(validRoutingLayers) {M1 M2 M3 M4 M5 M6}
set GVAR_amdLayVariables(amdLayoutBorderLPP) [list "PinBorder" "boundary"]
### end added by norayra

}
