#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xhost +
xsetroot -solid grey
vncconfig -iconic &
xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &

# Select a window manager
if [ -x /usr/bin/mwm -a ! -x /usr/bin/twm ]
then
    # SLES12 does not have twm, so use mwm -rjv 18-Sept-2015
    /usr/bin/mwm &
else
    # Everyone else gets twm
    twm &
fi

